# cargos.py
cargos_funciones = {
    1: 'Cobros',
    2: 'Jefe de Compras',
    3: 'Recepción de Pedidos',
    4: 'Esteticista',
    5: 'Gerente',
    6: 'Gestoría',
    7: 'Comercial',
    8: 'Administración',
    9: 'Director Administrativo',
    10: 'Abogado',
    11: 'Encargado',
    12: 'Asesoría',
    13: 'Director Técnico',
    14: 'Sin determinar',
    15: 'Confirming',
    16: 'Banco',
    17: 'Marido',
    18: 'Secretaria/o',
    19: 'Marketing',
    20: 'Socio/a',
    21: 'Peluquera',
    22: 'Envío de facturas electrónicas',
    23: 'Técnico',
    24: 'Operadora',
    25: 'Community Manager',
    26: 'Notificaciones Agencia de Transportes',
    27: 'Información productos en depósito',
    28: 'Envío por correo facturas trimestre',
}